#!/bin/bash
#
# Based on 2011 script by Axel Kohlmeyer <akohlmey@gmail.com>,
# https://sites.google.com/site/akohlmey/random-hacks/nvidia-gpu-coolness
#
# Ruby is required to run to script:
#
#     sudo apt-get install ruby2.3
#
# Already running an X server?
#
#     Make sure you are not running an X server.  This tool is meant
#     only for headless systems (no display attached).
#
# Suggested usage:
#
#    cd nvidia-fan-control
#    sudo ./fan-control
#
# Seems to work fine on headless ubuntu systems with one or two compute GPUs.
# Not intended to run automatically at system startup, sorry!  However,
# once kicked off, should be good until reboot.

# Check the installation of ruby
command -v ruby >/dev/null 2>&1 || { echo "Ruby ( >2 ) is required. Aborting." >&2; exit 1; }

# Check permission
if (( $EUID != 0 )); then
    echo "Please run as root"
    exit
fi

SCRIPT=`realpath $0`
DIR=`dirname $SCRIPT`

/usr/bin/nvidia-smi -pm 1

# Convert INT and TERM to EXIT, and kill all sub-porcesses on exit
trap "exit" INT TERM
trap "kill 0" EXIT

# we need to launch the X server once for each display
# making each of the PCI IDs the primary device in turn.

# get PCI bus ids of Nvidia cards and convert from hexadecimal to decimal. watch out for the falling toothpicks.
pciid=`lspci  | sed -n -e '/VGA compatib.*NVIDIA/s/^\(..\):\(..\).\(.\).*/printf "PCI:%d:%d:%d\\\\\\\\n" 0x\1 0x\2 0x\3;/p'`
display=0
for device in `eval ${pciid}`
do \
    CFG=`mktemp /tmp/xorg-XXXXXXXX.conf`
    sed -e s,@GPU_BUS_ID@,${device},    \
        -e s,@SET_GPU_DIR@,${DIR}, \
        ${DIR}/xorg.conf >> ${CFG}
    # we keep one X server per GPU running indefinitely
    # (if we let the X server die, the fan config does not persist, no matter what else)
    xinit ${DIR}/auto-fan-control.rb -- :${display} -once -config ${CFG} &
    display=$((display+1))
    sleep 5
    rm -f ${CFG}
done

# Just wait for sub-processes
for job in `jobs -p`
do
    wait $job
done
